/** Declaration file generated by dts-gen */

export function install(Vue: any): void;

export function loadGoogleCharts(...args: any[]): any;

export namespace GChart {
    const name: string;

    const props: {
        createChart: {
            type: any;
        };
        data: {
            default: any;
            type: any[];
        };
        events: {
            type: any;
        };
        options: {
            default: any;
            type: any;
        };
        resizeDebounce: {
            default: number;
            type: any;
        };
        settings: {
            default: any;
            type: any;
        };
        type: {
            type: any;
        };
        version: {
            default: string;
            type: any;
        };
    };

    const staticRenderFns: any[];

    function beforeDestroy(): void;

    function data(): any;

    function mounted(): void;

    function render(): any;

    namespace methods {
        function attachListeners(): void;

        function createChartObject(): any;

        function drawChart(): void;

        function getValidChartData(): any;

    }

    namespace watch {
        function type(value: any): void;

        namespace data {
            const deep: boolean;

            function handler(): void;

        }

        namespace options {
            const deep: boolean;

            function handler(): void;

        }

    }

}

